name: practice
on: push
jobs:
  lint_test_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./19
    steps:
      - name: get repo
        uses: actions/checkout@v4
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
  deploy:
    needs: lint_test_build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./19
    steps:
      - name: get repo
        uses: actions/checkout@v4
      - name: run the app
        run: npm run dev
